services:
  postgres:
    image: postgres:15
    container_name: postgres-api-crud
    environment:
      POSTGRES_DB: apicrud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - apicrud-network

volumes:
  postgres-data:

networks:
  apicrud-network:
    driver: bridge
